apiVersion: v1
kind: List
metadata: {}
items:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      pipeline.alpha.openshift.io/uses: '[{"name": "jws-app", "namespace": "", "kind": "DeploymentConfig"}]'
    name: jws-app-pipeline
  spec:
    source:
      git:
        uri: https://github.com/cerabi2010/simple.git
      type: Git
    strategy:
      type: JenkinsPipeline
      jenkinsPipelineStrategy:
        env:
          - name: MAVEN_MIRROR_URL
            value: http://nexus.apps.ocp4.rp.com:8081/repository/maven-proxy1/
        jenkinsfilePath: Jenkinsfile
